export const NAVIGATOR_NAMES = {
  ACCOUNTS: 'ACCOUNTS_NAVIGATOR',
  GROUPS: 'GROUPS_NAVIGATOR',
};

export const ACCOUNTS_NAVIGATOR_SCREEN_NAMES = {
  TRANSACTIONS: 'TRANSACTIONS',
  TRANSACTIONS_BY_TAG_ID: 'TRANSACTIONS_BY_TAG_ID',
  ACCOUNTS: 'ACCOUNTS',
  TRANSACTIONS_BY_ACCOUNT: 'TRANSACTIONS_BY_ACCOUNT',
};
