export const SCREEN_NAMES = {
  ACCOUNTS: 'ACCOUNTS',
  GROUPS: 'GROUPS_NAVIGATOR',
  HOME: 'HOME',
  TRANSACTIONS_BY_ACCOUNT: 'TRANSACTIONS_BY_ACCOUNT',
  TRANSACTIONS_BY_TAG_AND_ACCOUNT: 'TRANSACTIONS_BY_TAG_AND_ACCOUNT',
};
