export const SWR_KEY_COMPONENTS = {
  TRANSACTIONS: 'TRANSACTIONS',
  TRANSACTION: 'TRANSACTION',
  TAGS: 'TAGS',
  TAG: 'TAG',
  ACCOUNTS: 'ACCOUNTS',
  ACCOUNT: 'ACCOUNT',
  DTO: 'DTO',
  DTOS: 'DTOS',
  GROUPS: 'GROUPS',
  GROUP: 'GROUP',
};
